# -*- coding: utf-8 -*-
"""
Created on Thu May 27 13:48:45 2021

@author: jaywo
"""

# trackId_mapping = {
#     'Wentworth Park': [200],
#     'Dapto': [201],
#     'Bulli': [202],
#     'Casino': [203],
#     'Cessnook': [204],
#     'Gosford': [205],
#     'Grafton': [206],
#     'Lismore': [207],
#     'Maitland': [208],
#     'Muswellbrook': [209],
#     'Newcastle': [210],
#     'Nowra': [211],
#     'Orange': [212],
#     'Penrith': [213],
#     'Richmond': [214],
#     'Moree': [215],
#     'Wyong': [216],
#     'Singleton': [217],
#     'Taree': [218],
#     'Temora': [219],
#     'Wagga Wagga': [220],
#     'Wauchope': [221],
#     'Tweed Heads': [222],
#     'Albury': [223],
#     'Appin': [224],
#     'Armidale': [225],
#     'Bathurst': [226],
#     'Broken Hill': [227],
#     'Coonabarabran': [228],
#     'Coonamble': [229],
#     'Cootamundra': [230],
#     'Dubbo': [231],
#     'Forbes': [232],
#     'Goulburn': [233],
#     'Griffith': [234],
#     'Gunnedah': [235],
#     'Harold Park': [236],
#     'Kempsey': [237],
#     'Lithgow': [238],
#     'Moss Vale': [239],
#     'Mudgee': [240],
#     'Queanbeyan': [241],
#     'Tamworth': [242],
#     'Wollongong': [243],
#     'Young': [244],
#     'Cowra': [245],
#     'Wentworth': [246],
#     'Narrabi': [247],
#     'Potts Park': [248],
#     'The Gardens': [249],
#     'Canberra': [250],
#     'The Meadows': [300, 315],
#     'Sandown Park': [301, 314],
#     'Ballarat': [302],
#     'Bendigo': [303],
#     'Cranbourne': [304],
#     'Geelong': [305],
#     'Healesville': [306],
#     'Horsham': [307],
#     'Shepparton': [308],
#     'Sale': [309],
#     'Traralgon': [310],
#     'Wangaratta': [311],
#     'Warragul': [312],
#     'Warrnambool': [313],
#     'Brisbane': [400],
#     'Beenleigh': [401],
#     'Bundaberg': [402],
#     'Cairns': [403],
#     'Capalaba': [404],
#     'Gabba': [405],
#     'Gold Coast': [406],
#     'Ipswich': [407],
#     'Lawnton': [408],
#     'Ayr': [409],
#     'Mackay': [410],
#     'Mt Isa': [411],
#     'Rockhampton': [412],
#     'Townsville': [413],
#     'Toowoomba': [414],
#     'Angle Park': [500],
#     'Barmera': [501],
#     'Gawler': [502],
#     'Kulpara': [503],
#     'Mount Gambier': [504],
#     'Port Augusta': [505],
#     'Port Lincoln': [506],
#     'Port Pirie': [507],
#     'Strathalbyn': [508],
#     'Whyalla': [509],
#     'Cannington': [600],
#     'Mandurah': [601],
#     'Northam': [602],
#     'Hobart': [700],
#     'Launceston': [701],
#     'Devonport': [702],
#     'Darwin': [800],
#     'Christchurch': [900],
#     'Wanganui': [901],
#     'Manawatu': [902],
#     'Auckland': [903],
#     'Waikato': [904],
#     'Otago': [905],
#     'Southland': [906],
#     'Wairarapa': [907],
#     'Wellington': [908],
#     'Tokoroa': [909],
#     'Taranaki': [910],
#     'Palmerston North': [911],
#     'Ashburton': [912]
#     }

trackCodes = [
    {'trackCode': 200, 'trackName': 'Wentworth Park', 'State': 'NSW'},
    {'trackCode': 201, 'trackName': 'Dapto', 'State': 'NSW'},
    {'trackCode': 202, 'trackName': 'Bulli', 'State': 'NSW'},
    {'trackCode': 203, 'trackName': 'Casino', 'State': 'NSW'},
    {'trackCode': 204, 'trackName': 'Cessnock', 'State': 'NSW'},    
    {'trackCode': 205, 'trackName': 'Gosford', 'State': 'NSW'},
    {'trackCode': 206, 'trackName': 'Grafton', 'State': 'NSW'}, 
    {'trackCode': 207, 'trackName': 'Lismore', 'State': 'NSW'}, 
    {'trackCode': 208, 'trackName': 'Maitland', 'State': 'NSW'}, 
    {'trackCode': 209, 'trackName': 'Muswellbrook', 'State': 'NSW'}, 
    {'trackCode': 210, 'trackName': 'Newcastle', 'State': 'NSW'}, 
    {'trackCode': 211, 'trackName': 'Nowra', 'State': 'NSW'}, 
    {'trackCode': 212, 'trackName': 'Orange', 'State': 'NSW'}, 
    {'trackCode': 213, 'trackName': 'Penrith', 'State': 'NSW'}, 
    {'trackCode': 214, 'trackName': 'Richmond', 'State': 'NSW'}, 
    {'trackCode': 215, 'trackName': 'Moree', 'State': 'NSW'}, 
    {'trackCode': 216, 'trackName': 'Wyong', 'State': 'NSW'}, 
    {'trackCode': 218, 'trackName': 'Taree', 'State': 'NSW'}, 
    {'trackCode': 219, 'trackName': 'Temora', 'State': 'NSW'}, 
    {'trackCode': 220, 'trackName': 'Wagga Wagga', 'State': 'NSW'}, 
    {'trackCode': 221, 'trackName': 'Wauchope', 'State': 'NSW'}, 
    {'trackCode': 223, 'trackName': 'Albury', 'State': 'NSW'}, 
    {'trackCode': 225, 'trackName': 'Armidale', 'State': 'NSW'}, 
    {'trackCode': 226, 'trackName': 'Bathurst', 'State': 'NSW'}, 
    {'trackCode': 227, 'trackName': 'Broke Hill', 'State': 'NSW'}, 
    {'trackCode': 228, 'trackName': 'Coonabarabran', 'State': 'NSW'}, 
    {'trackCode': 229, 'trackName': 'Coonamble', 'State': 'NSW'}, 
    {'trackCode': 230, 'trackName': 'Cootamundra', 'State': 'NSW'}, 
    {'trackCode': 231, 'trackName': 'Dubbo', 'State': 'NSW'}, 
    {'trackCode': 232, 'trackName': 'Forbes', 'State': 'NSW'}, 
    {'trackCode': 233, 'trackName': 'Goulburn', 'State': 'NSW'}, 
    {'trackCode': 234, 'trackName': 'Griffith', 'State': 'NSW'}, 
    {'trackCode': 235, 'trackName': 'Gunnedah', 'State': 'NSW'}, 
    {'trackCode': 236, 'trackName': 'Harold Park', 'State': 'NSW'}, 
    {'trackCode': 237, 'trackName': 'Kempsey', 'State': 'NSW'}, 
    {'trackCode': 238, 'trackName': 'Lithgow', 'State': 'NSW'}, 
    {'trackCode': 239, 'trackName': 'Moss Vale', 'State': 'NSW'}, 
    {'trackCode': 240, 'trackName': 'Mudgee', 'State': 'NSW'}, 
    {'trackCode': 241, 'trackName': 'Queanbeyan', 'State': 'NSW'}, 
    {'trackCode': 242, 'trackName': 'Tamworth', 'State': 'NSW'}, 
    {'trackCode': 243, 'trackName': 'Wollongong', 'State': 'NSW'}, 
    {'trackCode': 244, 'trackName': 'Young', 'State': 'NSW'}, 
    {'trackCode': 245, 'trackName': 'Cowra', 'State': 'NSW'}, 
    {'trackCode': 246, 'trackName': 'Wentworth', 'State': 'NSW'}, 
    {'trackCode': 247, 'trackName': 'Narrabri', 'State': 'NSW'}, 
    {'trackCode': 248, 'trackName': 'Potts Park', 'State': 'NSW'}, 
    {'trackCode': 249, 'trackName': 'The Gardens', 'State': 'NSW'}, 
    {'trackCode': 250, 'trackName': 'Canberra', 'State': 'NSW'}, 
    {'trackCode': 251, 'trackName': 'Richmond', 'State': 'NSW'}, 
    {'trackCode': 300, 'trackName': 'The Meadows', 'State': 'VIC'}, 
    {'trackCode': 301, 'trackName': 'Sandown Park', 'State': 'VIC'}, 
    {'trackCode': 302, 'trackName': 'Ballarat', 'State': 'VIC'}, 
    {'trackCode': 303, 'trackName': 'Bendigo', 'State': 'VIC'}, 
    {'trackCode': 304, 'trackName': 'Cranbourne', 'State': 'VIC'}, 
    {'trackCode': 305, 'trackName': 'Geelong', 'State': 'VIC'}, 
    {'trackCode': 306, 'trackName': 'Healesville', 'State': 'VIC'}, 
    {'trackCode': 307, 'trackName': 'Horsham', 'State': 'VIC'}, 
    {'trackCode': 308, 'trackName': 'Shepparton', 'State': 'VIC'}, 
    {'trackCode': 309, 'trackName': 'Sale', 'State': 'VIC'}, 
    {'trackCode': 310, 'trackName': 'Traralgon', 'State': 'VIC'}, 
    {'trackCode': 311, 'trackName': 'Wangaratta', 'State': 'VIC'}, 
    {'trackCode': 312, 'trackName': 'Warragul', 'State': 'VIC'}, 
    {'trackCode': 313, 'trackName': 'Warrnambool', 'State': 'VIC'}, 
    {'trackCode': 314, 'trackName': 'Sandown Park', 'State': 'VIC'}, 
    {'trackCode': 315, 'trackName': 'The Meadows', 'State': 'VIC'}, 
    {'trackCode': 363, 'trackName': 'Warrnambool', 'State': 'VIC'}, 
    {'trackCode': 400, 'trackName': 'Albion Park', 'State': 'QLD'}, 
    {'trackCode': 401, 'trackName': 'Beenleigh', 'State': 'QLD'}, 
    {'trackCode': 402, 'trackName': 'Bundaberg', 'State': 'QLD'}, 
    {'trackCode': 403, 'trackName': 'Cairns', 'State': 'QLD'}, 
    {'trackCode': 404, 'trackName': 'Capalaba', 'State': 'QLD'}, 
    {'trackCode': 405, 'trackName': 'Gabba', 'State': 'QLD'}, 
    {'trackCode': 406, 'trackName': 'Gold Coast', 'State': 'QLD'}, 
    {'trackCode': 407, 'trackName': 'Ipswich', 'State': 'QLD'}, 
    {'trackCode': 408, 'trackName': 'Lawnton', 'State': 'QLD'}, 
    {'trackCode': 409, 'trackName': 'Ayr', 'State': 'QLD'}, 
    {'trackCode': 410, 'trackName': 'Mackay', 'State': 'QLD'}, 
    {'trackCode': 411, 'trackName': 'Mt Isa', 'State': 'QLD'}, 
    {'trackCode': 412, 'trackName': 'Rockhampton', 'State': 'QLD'}, 
    {'trackCode': 413, 'trackName': 'Townsville', 'State': 'QLD'}, 
    {'trackCode': 414, 'trackName': 'Toowoomba', 'State': 'QLD'}, 
    {'trackCode': 500, 'trackName': 'Angle Park', 'State': 'SA'}, 
    {'trackCode': 501, 'trackName': 'Barmera', 'State': 'SA'}, 
    {'trackCode': 502, 'trackName': 'Gawler', 'State': 'SA'}, 
    {'trackCode': 503, 'trackName': 'Kulpara', 'State': 'SA'}, 
    {'trackCode': 504, 'trackName': 'Mount Gambier', 'State': 'SA'}, 
    {'trackCode': 505, 'trackName': 'Port Augusta', 'State': 'SA'}, 
    {'trackCode': 506, 'trackName': 'Port Lincoln', 'State': 'SA'}, 
    {'trackCode': 507, 'trackName': 'Port Pirie', 'State': 'SA'}, 
    {'trackCode': 508, 'trackName': 'Strathalbyn', 'State': 'SA'}, 
    {'trackCode': 509, 'trackName': 'Whyalla', 'State': 'SA'}, 
    {'trackCode': 510, 'trackName': 'Murray Bridge', 'State': 'SA'}, 
    {'trackCode': 511, 'trackName': 'Murray Bridge', 'State': 'SA'}, 
    {'trackCode': 600, 'trackName': 'Cannington', 'State': 'WA'}, 
    {'trackCode': 601, 'trackName': 'Mandurah', 'State': 'WA'}, 
    {'trackCode': 602, 'trackName': 'Northam', 'State': 'WA'}, 
    {'trackCode': 700, 'trackName': 'Hobart', 'State': 'TAS'}, 
    {'trackCode': 701, 'trackName': 'Launceston', 'State': 'TAS'}, 
    {'trackCode': 702, 'trackName': 'Devonport', 'State': 'TAS'}, 
    {'trackCode': 800, 'trackName': 'Darwin', 'State': 'NT'}, 
    {'trackCode': 900, 'trackName': 'Christchurch', 'State': 'NZ'}, 
    {'trackCode': 901, 'trackName': 'Wanganui', 'State': 'NZ'}, 
    {'trackCode': 902, 'trackName': 'Manawatu', 'State': 'NZ'}, 
    {'trackCode': 903, 'trackName': 'Auckland', 'State': 'NZ'}, 
    {'trackCode': 904, 'trackName': 'Waikato', 'State': 'NZ'}, 
    {'trackCode': 905, 'trackName': 'Otago', 'State': 'NZ'}, 
    {'trackCode': 906, 'trackName': 'Southland', 'State': 'NZ'}, 
    {'trackCode': 907, 'trackName': 'Wairarapa', 'State': 'NZ'}, 
    {'trackCode': 908, 'trackName': 'Wellington', 'State': 'NZ'}, 
    {'trackCode': 909, 'trackName': 'Tokoroa', 'State': 'NZ'}, 
    {'trackCode': 910, 'trackName': 'Taranaki', 'State': 'NZ'}, 
    {'trackCode': 911, 'trackName': 'Palmerston North', 'State': 'NZ'}, 
    {'trackCode': 912, 'trackName': 'Ashburton', 'State': 'NZ'},         
    ]



timeslot_mapping = {
    'Twilight': 't',
    'Morning': 'm',
    'Day': 'd',
    'Night': 'n'
    }

bfTrackAbbrev_mapping = {
    'Addington': 'Addi',
    'Albion Park': 'APrk',
    'Albury': 'Alby',
    'Angle Park': 'AnPk',
    'Armidale': 'Armi',
    'Ascot Park': 'AsPk',
    'Ashburton': 'Ashb',
    'Auckland': 'Mkau',
    'Ayr': 'Ayr',
    'Ballarat': 'Ball',
    'Barmera': 'Barm',
    'Bathurst': 'Bath',
    'Beenleigh': 'Been',
    'Bendigo': 'Bend',
    'Bulli': 'Bull',
    'Broken Hill': 'BrnH',
    'Bundaberg': 'Bund',
    'Cairns': 'Crns',
    'Cambridge': 'Camb',
    'Canberra': 'Canb',
    'Cannington': 'Cann',
    'Capalaba': 'Capa',
    'Casino': 'Casi',
    'Cessnock': 'Cess',
    'Christchurch': 'Addi',
    'Coonabarabran': 'Cona',
    'Coonamble': 'Cnbl',
    'Cootamundra': 'Coot',
    'Cowra': 'Cowr',
    'Cranbourne': 'Cran',
    'Dapto': 'Dapt',
    'Darwin': 'Darw',
    'Devonport': 'Devn',
    'Dubbo': 'Dubb',
    'Eagle Farm': 'EFrm',
    'Forbes': 'Forb',
    'Forbury Park': 'FPrk',
    'Gabba': 'Gabb',
    'Gawler': 'Gawl',
    'Geelong': 'Geel',
    'Gold Coast': 'GCst',
    'Gosford': 'Gosf',
    'Goulburn': 'Goul',
    'Grafton': 'Graf',
    'Griffith': 'Grif',
    'Gunnedah': 'Gunn',
    'Harold Park': 'HPrk',
    'Hatrick': 'Hatr',
    'Healesville': 'Heal',
    'Hobart': 'Hoba',
    'Horsham': 'Hshm',
    'Ipswich': 'Ipsw',
    'Kempsey': 'Kemp',
    'Kulpara': 'Kulp',
    'Lawnton': 'Lawn',
    'Launceston': 'Laun',
    'Lismore': 'Lism',
    'Lithgow': 'Lith',
    'Mackay': 'Mack',
    'Maitland': 'Mait',
    'Manawatu': 'Mana',
    'Mandurah': 'Mand',
    'Manukau': 'Mkau',
    'Menangle': 'Mngl',
    'Moree': 'More',
    'Mount Gambier': 'MGam',
    'Moss Vale': 'Moss',
    'Mt Isa': 'MIsa',
    'Mudgee': 'Mudg',
    'Murray Bridge': 'MBdg',
    'Muswellbrook': 'Musw',
    'Narrabri': 'Nbri',
    'Newcastle': 'Newc',
    'New Zealand': 'NewZ',
    'Northam': 'Nort',
    'Nowra': 'Nowr',
    'Orange': 'Orng',
    'Otago': 'FPrk',
    'Palmerston North': 'Mana',
    'Penrith': 'Penr',
    'Port Augusta': 'PAug',
    'Port Macquarie': 'PMaq',
    'Port Lincoln': 'PLin',
    'Port Pirie': 'PtPr',
    'Potts Park': 'Pott',
    'Queanbeyan': 'Quea',
    'Randwick': 'Rand',
    'Richmond': 'Rich',
    'Rockhampton': 'Rock',
    'Sale': 'Sale',
    'Sandown': 'Sand',
    'Sandown Park': 'SPrk',
    'Shepparton': 'Shep',
    'Southland': 'AsPk',
    'Strathalbyn': 'Stra',
    'Tamworth': 'Tamw',
    'Taranaki': 'Tara',
    'Taree': 'Tare',
    'Temora': 'Temo',
    'The Gardens': 'Gard',
    'The Meadows': 'Mead',
    'Tokoroa': 'Toko',
    'Toowoomba': 'Toow',
    'Townsville': 'Town',
    'Traralgon': 'Trar',
    'Wagga': 'Wagg',
    'Wagga Wagga': 'Wagg',
    'Waikato': 'Camb',
    'Wairarapa': 'Wair',
    'Wanganui': 'Hatr',
    'Wangaratta': 'Wang',
    'Warragul': 'Wgul',
    'Warrnambool': 'Warr',
    'Wauchope': 'Wchp',
    'Wellington': 'Well',
    'Wentworth': 'WPrk',
    'Wentworth Park': 'WPrk',
    'Whyalla': 'Whya',
    'Wollongong': 'Woll',
    'Wyong': 'Wyng',
    'Young': 'Youn'
    }

track = {
    'Hatrick': 'Wanganui (NZ)',
    'Addington': 'Christchurch (NZ)',
    'Forbury Park': 'Otago (NZ)',
    'Manawatu': 'Pamerston Nth (NZ)',
    'Manukau': 'Auckland (NZ)',
    'Ashburton': 'Ashburton (NZ)',
    'Cambridge': 'Waikato (NZ)',
    'Ascot Park': 'Southland (NZ)'
    }


